// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

// Replace these values with your actual Supabase project details
const SUPABASE_URL = "https://qxmmsuakpqgcfhmngmjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4bW1zdWFrcHFnY2ZobW5nbWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODEzNzcsImV4cCI6MjA1OTA1NzM3N30.BkT-HrDlR2HJ6iAhuaIFMD7H_jRFIu0Y9hpiSyU4EHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a dummy database type until a real one is available
type Database = any;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
